name: Build and Run SSH Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Go Rice
      run: go get github.com/GeertJohan/go.rice/rice

    - name: Install sshdog/daemon package
      run: go get github.com/shineuk/sshdog/daemon
    - name: Install sshdog/daemon and sshdog/pty packages
      run: |
       go get github.com/shineuk/sshdog/daemon
       go get github.com/shineuk/sshdog/pty
       
    - name: Build the Go project and embed static files using Rice
      run: |
        go build . -o sshdog
        ls

    - name: Generate SSH keys
      run: |
        ssh-keygen -t rsa -b 2048 -N '' -f config/ssh_host_rsa_key

    - name: Set SSH port
      run: echo "2222" > config/port

    - name: Copy authorized keys
      run: cp config/ssh_host_rsa_key.pub config/authorized_keys

    - name: Cross-compile for multiple platforms
      run: |
        rice append --exec sshdog
