name: Build and Run SSH Server

on:
  workflow_dispatch:  # 这里将事件触发器更改为 workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Go Rice
      run: go get github.com/GeertJohan/go.rice/rice

    - name: Build the Go project and embed static files using Rice
      run: |
        go build .
        rice embed-go

    - name: Generate SSH keys
      run: |
        ssh-keygen -t rsa -b 2048 -N '' -f config/ssh_host_rsa_key

    - name: Set SSH port
      run: echo "2222" > config/port

    - name: Copy authorized keys
      run: cp config/ssh_host_rsa_key.pub config/authorized_keys

    - name: Cross-compile for multiple platforms
      run: |
        env GOOS=linux GOARCH=amd64 go build -o sshdog-linux-amd64
        env GOOS=linux GOARCH=arm64 go build -o sshdog-linux-arm64
        env GOOS=windows GOARCH=amd64 go build -o sshdog-windows-amd64.exe
        env GOOS=darwin GOARCH=amd64 go build -o sshdog-darwin-amd64

    - name: Create release
      run: |
        zip sshdog-linux-amd64.zip sshdog-linux-amd64
        zip sshdog-linux-arm64.zip sshdog-linux-arm64
        zip sshdog-windows-amd64.zip sshdog-windows-amd64.exe
        zip sshdog-darwin-amd64.zip sshdog-darwin-amd64
