name: Build and Run SSH Server

on:
  workflow_dispatch:  # 这里将事件触发器更改为 workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install Go Rice
      run: go get github.com/GeertJohan/go.rice/rice

    - name: Build the Go project and embed static files using Rice
      run: |
        go build .
        rice embed-go

    - name: Generate SSH keys
      run: |
        ssh-keygen -t rsa -b 2048 -N '' -f config/ssh_host_rsa_key

    - name: Set SSH port
      run: echo "2222" > config/port

    - name: Copy authorized keys
      run: cp ~/.ssh/id_rsa.pub config/authorized_keys

    - name: Run SSH server
      run: ./sshdog
